/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_plugin_usage_ledger_usageLedgerPlugin_snapshot_parameter_0$schema = z.union([z.undefined(), z.object({
  'workspace': z.union([z.undefined(), z.literal(null), z.string()]).readonly().optional(),
  'days': z.union([z.undefined(), z.number()]).readonly().optional(),
  'timeZone': z.union([z.undefined(), z.string()]).readonly().optional(),
})])
const dsh_plugin_usage_ledger_usageLedgerPlugin_snapshot_result$schema = z.object({
  'workspace': z.union([z.literal(null), z.string()]).readonly(),
  'days': z.number().readonly(),
  'fromDay': z.string().readonly(),
  'throughDay': z.string().readonly(),
  'timeZone': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'events': z.array(z.object({
  'at': z.number().readonly(),
  'workspace': z.union([z.literal(null), z.string()]).readonly(),
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
  'outcome': z.union([z.literal("started"), z.literal("success"), z.literal("failure"), z.literal("aborted")]).readonly(),
  'retried': z.boolean().readonly(),
  'inputTokens': z.union([z.undefined(), z.number()]).readonly().optional(),
  'outputTokens': z.union([z.undefined(), z.number()]).readonly().optional(),
  'cacheReadTokens': z.union([z.undefined(), z.number()]).readonly().optional(),
  'cacheWriteTokens': z.union([z.undefined(), z.number()]).readonly().optional(),
})).readonly(),
  'models': z.array(z.object({
  'workspace': z.union([z.literal(null), z.string()]).readonly(),
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
  'requests': z.number().readonly(),
  'successfulRequests': z.number().readonly(),
  'failedRequests': z.number().readonly(),
  'retryRequests': z.number().readonly(),
  'meteredRequests': z.number().readonly(),
  'unmeteredRequests': z.number().readonly(),
})).readonly(),
  'daily': z.array(z.object({
  'day': z.string().readonly(),
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
  'requests': z.number().readonly(),
  'successfulRequests': z.number().readonly(),
  'failedRequests': z.number().readonly(),
  'retryRequests': z.number().readonly(),
  'meteredRequests': z.number().readonly(),
  'unmeteredRequests': z.number().readonly(),
})).readonly(),
})

export const TYPERT = {
  package: 'dsh-plugin-usage-ledger',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-plugin-usage-ledger#usageLedgerPlugin/snapshot',
      service: 'usageLedger',
      namespace: 'usageLedgerPlugin',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-plugin-usage-ledger/types#UsageLedgerSnapshotRequest',
            schema: dsh_plugin_usage_ledger_usageLedgerPlugin_snapshot_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-plugin-usage-ledger/types#UsageLedgerSnapshot',
        schema: dsh_plugin_usage_ledger_usageLedgerPlugin_snapshot_result$schema,
      },
      sourceLocation: {"file":"src/host/index.ts","line":281,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host service that persists each final, failed, aborted, and retried provider call.",
        "summary": "Host service that persists each final, failed, aborted, and retried provider call.",
        "tags": [],
        "jsDoc": "/** Host service that persists each final, failed, aborted, and retried provider call. */",
        "key": "usageLedger",
        "exportName": "UsageLedgerService",
        "members": [
          {
            "kind": "method",
            "name": "snapshot",
            "signature": "@Remote('snapshot') async snapshot(request?: UsageLedgerSnapshotRequest): Promise<UsageLedgerSnapshot>",
            "summary": "Return a bounded, read-only summary derived from idempotent call records.",
            "jsDoc": "/**\n * Return a bounded, read-only summary derived from idempotent call records.\n * @param request - optional workspace, calendar-day, and timezone filters.\n * @returns the usage snapshot after all queued session events are applied.\n */"
          }
        ],
        "types": [
          {
            "name": "UsageLedgerDailyRow",
            "declaration": "export interface UsageLedgerDailyRow {\n    readonly day: string;\n    readonly inputTokens: number;\n    readonly outputTokens: number;\n    readonly cacheReadTokens: number;\n    readonly cacheWriteTokens: number;\n    readonly requests: number;\n    readonly successfulRequests: number;\n    readonly failedRequests: number;\n    readonly retryRequests: number;\n    readonly meteredRequests: number;\n    readonly unmeteredRequests: number;\n}"
          },
          {
            "name": "UsageLedgerEvent",
            "declaration": "export interface UsageLedgerEvent {\n    readonly at: number;\n    readonly workspace: string | null;\n    readonly provider: string;\n    readonly model: string;\n    readonly outcome: 'started' | 'success' | 'failure' | 'aborted';\n    readonly retried: boolean;\n    readonly inputTokens?: number;\n    readonly outputTokens?: number;\n    readonly cacheReadTokens?: number;\n    readonly cacheWriteTokens?: number;\n}"
          },
          {
            "name": "UsageLedgerModelRow",
            "declaration": "export interface UsageLedgerModelRow {\n    readonly workspace: string | null;\n    readonly provider: string;\n    readonly model: string;\n    readonly inputTokens: number;\n    readonly outputTokens: number;\n    readonly cacheReadTokens: number;\n    readonly cacheWriteTokens: number;\n    readonly requests: number;\n    readonly successfulRequests: number;\n    readonly failedRequests: number;\n    readonly retryRequests: number;\n    readonly meteredRequests: number;\n    readonly unmeteredRequests: number;\n}"
          },
          {
            "name": "UsageLedgerSnapshot",
            "declaration": "export interface UsageLedgerSnapshot {\n    readonly workspace: string | null;\n    readonly days: number;\n    readonly fromDay: string;\n    readonly throughDay: string;\n    readonly timeZone: string;\n    readonly updatedAt: string;\n    readonly events: readonly UsageLedgerEvent[];\n    readonly models: readonly UsageLedgerModelRow[];\n    readonly daily: readonly UsageLedgerDailyRow[];\n}"
          },
          {
            "name": "UsageLedgerSnapshotRequest",
            "declaration": "export interface UsageLedgerSnapshotRequest {\n    readonly workspace?: string | null;\n    readonly days?: number;\n    readonly timeZone?: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
