/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { UsageLedgerSnapshot, UsageLedgerSnapshotRequest } from '../host/types.ts'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$75736167654c6564676572506c7567696e {
    snapshot: (request?: UsageLedgerSnapshotRequest) => Promise<RemoteResult<UsageLedgerSnapshot>>
  }
  interface TypertRemoteMap {
    'usageLedgerPlugin/snapshot': (request?: UsageLedgerSnapshotRequest) => Promise<RemoteResult<UsageLedgerSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'usageLedgerPlugin': TypertRemoteNamespace$75736167654c6564676572506c7567696e
  }
}

/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const dsh_plugin_usage_ledger_usageLedgerPlugin_snapshot_parameter_0$schema = z.union([z.undefined(), z.object({
  'workspace': z.union([z.undefined(), z.literal(null), z.string()]).readonly().optional(),
  'days': z.union([z.undefined(), z.number()]).readonly().optional(),
  'timeZone': z.union([z.undefined(), z.string()]).readonly().optional(),
})])
const dsh_plugin_usage_ledger_usageLedgerPlugin_snapshot_result$schema = z.object({
  'workspace': z.union([z.literal(null), z.string()]).readonly(),
  'days': z.number().readonly(),
  'fromDay': z.string().readonly(),
  'throughDay': z.string().readonly(),
  'timeZone': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'events': z.array(z.object({
  'at': z.number().readonly(),
  'workspace': z.union([z.literal(null), z.string()]).readonly(),
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
  'outcome': z.union([z.literal("started"), z.literal("success"), z.literal("failure"), z.literal("aborted")]).readonly(),
  'retried': z.boolean().readonly(),
  'inputTokens': z.union([z.undefined(), z.number()]).readonly().optional(),
  'outputTokens': z.union([z.undefined(), z.number()]).readonly().optional(),
  'cacheReadTokens': z.union([z.undefined(), z.number()]).readonly().optional(),
  'cacheWriteTokens': z.union([z.undefined(), z.number()]).readonly().optional(),
})).readonly(),
  'models': z.array(z.object({
  'workspace': z.union([z.literal(null), z.string()]).readonly(),
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
  'requests': z.number().readonly(),
  'successfulRequests': z.number().readonly(),
  'failedRequests': z.number().readonly(),
  'retryRequests': z.number().readonly(),
  'meteredRequests': z.number().readonly(),
  'unmeteredRequests': z.number().readonly(),
})).readonly(),
  'daily': z.array(z.object({
  'day': z.string().readonly(),
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
  'requests': z.number().readonly(),
  'successfulRequests': z.number().readonly(),
  'failedRequests': z.number().readonly(),
  'retryRequests': z.number().readonly(),
  'meteredRequests': z.number().readonly(),
  'unmeteredRequests': z.number().readonly(),
})).readonly(),
})

export const TYPERT_REMOTE: TypertRemoteContribution = {
  package: 'dsh-plugin-usage-ledger',
  descriptors: [
    {
      id: 'dsh-plugin-usage-ledger#usageLedgerPlugin/snapshot',
      service: 'usageLedger',
      namespace: 'usageLedgerPlugin',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-plugin-usage-ledger/types#UsageLedgerSnapshotRequest',
            schema: dsh_plugin_usage_ledger_usageLedgerPlugin_snapshot_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-plugin-usage-ledger/types#UsageLedgerSnapshot',
        schema: dsh_plugin_usage_ledger_usageLedgerPlugin_snapshot_result$schema,
      },
      sourceLocation: {"file":"src/host/index.ts","line":437,"column":9},
    },
  ],
}

export default TYPERT_REMOTE
